"""Outcome Neural Network — gated at nn_min_days.

A lightweight MLP that learns per-outcome biomarker deltas from real user data
augmented with synthetic samples generated by the Gaussian copula.

Architecture:  Input(N) → Linear(128) → ReLU → Linear(64) → ReLU → Linear(7)
Loss:          MSE with real data weighted 3× relative to synthetic samples.
Optimizer:     Adam(lr=1e-3)

Saves the trained model to models/user_{id}/outcome_nn.pt for two uses:
  1. Inference path at fidelity 3 when active_tier == "nn"
  2. Dual-path comparison vs the Ridge ML suite (via record_nn_comparison)
"""

from __future__ import annotations

import os
from typing import Any

import numpy as np

MODELS_ROOT = os.path.join(os.path.dirname(__file__), "..", "models")


def _model_dir(user_id: int) -> str:
    path = os.path.join(MODELS_ROOT, f"user_{user_id}")
    os.makedirs(path, exist_ok=True)
    return path


# ---------------------------------------------------------------------------
# Network definition
# ---------------------------------------------------------------------------

def _build_model(n_features: int, n_outputs: int = 7) -> Any:
    """Build the outcome NN.  Returns a torch.nn.Module."""
    import torch.nn as nn

    class OutcomeNN(nn.Module):
        def __init__(self, n_in: int, n_out: int):
            super().__init__()
            self.net = nn.Sequential(
                nn.Linear(n_in, 128),
                nn.ReLU(),
                nn.Linear(128, 64),
                nn.ReLU(),
                nn.Linear(64, n_out),
            )

        def forward(self, x):  # type: ignore[override]
            return self.net(x)

    return OutcomeNN(n_features, n_outputs)


# ---------------------------------------------------------------------------
# Synthetic data generation
# ---------------------------------------------------------------------------

def _generate_synthetic(
    distribution: Any,
    n_synthetic: int,
    n_features: int,
    n_outcomes: int,
    rng: np.random.Generator,
) -> tuple[np.ndarray, np.ndarray]:
    """Sample (X, Y) pairs from the copula distribution.

    X is filled with zeros for the ar/compliance columns (not in copula) and
    the 7 copula X-features for the controllable inputs.  This is intentionally
    rough — the real data provides the quality; synthetic gives volume.
    """
    try:
        from backend.distribution_calibration import sample_conditional, X_FEATURE_NAMES

        n_x_copula = len(X_FEATURE_NAMES)
        X_syn = np.zeros((n_synthetic, n_features))
        Y_syn = np.zeros((n_synthetic, n_outcomes))

        # Sample random X in a plausible physiological range
        # sleep_hours [4-10], bedtime cos/sin [-1,1], active_mins_h [0-3], ...
        low = np.array([4.0, -1.0, -1.0, 0.0, 0.0, 0.0, 0.0])
        high = np.array([10.0, 1.0, 1.0, 3.0, 5.0, 2.0, 25.0])

        for i in range(n_synthetic):
            x_copula = rng.uniform(low, high)
            X_syn[i, :n_x_copula] = x_copula
            # AR features and compliance stay at 0 (neutral)
            y = sample_conditional(distribution, x_copula, rng)
            n_y = min(len(y), n_outcomes)
            Y_syn[i, :n_y] = y[:n_y]

        return X_syn, Y_syn
    except Exception as e:
        print(f"[OutcomeNN] Synthetic generation error: {e}")
        return np.zeros((0, n_features)), np.zeros((0, n_outcomes))


# ---------------------------------------------------------------------------
# Training entry point
# ---------------------------------------------------------------------------

def train_outcome_nn(user_id: int) -> bool:
    """Train the outcome NN for a user.

    Uses real data (3× weight) + synthetic copula samples (1× weight).
    Gates on nn_min_days threshold.  Returns True if training succeeded.

    Saves to models/user_{user_id}/outcome_nn.pt.
    """
    import torch
    import torch.nn as nn
    import torch.optim as optim

    from backend.maturity_config import (
        count_paired_days,
        get_user_thresholds,
        record_nn_comparison,
    )
    from backend.feature_engineering import build_Xy_matrix
    from backend.outcome_models import load_outcome_models

    thresholds = get_user_thresholds(user_id)
    paired_days = count_paired_days(user_id)

    if paired_days < thresholds["nn_min_days"]:
        print(f"[OutcomeNN] user {user_id}: only {paired_days} days, need {thresholds['nn_min_days']}")
        return False

    # Load real data
    include_rolling = paired_days >= thresholds["ml_lag2_min_days"]
    X_real, Y_real, feature_names, outcome_names = build_Xy_matrix(
        user_id, include_rolling=include_rolling
    )

    if X_real.shape[0] < 10:
        print(f"[OutcomeNN] user {user_id}: too few rows ({X_real.shape[0]})")
        return False

    n_features = X_real.shape[1]
    n_outcomes = Y_real.shape[1]

    # Try to get copula distribution for synthetic data generation
    dist_path = os.path.join(MODELS_ROOT, f"user_{user_id}", "distribution.json")
    distribution = None
    if os.path.exists(dist_path):
        try:
            from backend.distribution_calibration import load_joint_distribution
            distribution = load_joint_distribution(user_id)
        except Exception as e:
            print(f"[OutcomeNN] Could not load distribution: {e}")

    # Generate synthetic samples (3× the real data count)
    n_synthetic = X_real.shape[0] * 3
    rng = np.random.default_rng(42 + user_id)

    if distribution is not None:
        X_syn, Y_syn = _generate_synthetic(distribution, n_synthetic, n_features, n_outcomes, rng)
    else:
        X_syn, Y_syn = np.zeros((0, n_features)), np.zeros((0, n_outcomes))

    # Build weighted training set: real gets weight 3, synthetic gets 1
    if X_syn.shape[0] > 0:
        X_all = np.vstack([X_real, X_syn])
        Y_all = np.vstack([Y_real, Y_syn])
        weights = np.array([3.0] * X_real.shape[0] + [1.0] * X_syn.shape[0])
    else:
        X_all = X_real
        Y_all = Y_real
        weights = np.ones(X_real.shape[0])

    # Normalise
    X_mean = X_all.mean(axis=0)
    X_std  = np.where(X_all.std(axis=0) < 1e-8, 1.0, X_all.std(axis=0))
    X_all_s = (X_all - X_mean) / X_std

    X_t = torch.FloatTensor(X_all_s)
    Y_t = torch.FloatTensor(Y_all)
    W_t = torch.FloatTensor(weights)

    model = _build_model(n_features, n_outcomes)
    optimizer = optim.Adam(model.parameters(), lr=1e-3)
    mse_loss = nn.MSELoss(reduction="none")

    # Training loop (300 epochs)
    model.train()
    for epoch in range(300):
        optimizer.zero_grad()
        pred = model(X_t)
        loss_mat = mse_loss(pred, Y_t)              # (N, 7)
        loss_per_sample = loss_mat.mean(dim=1)       # (N,)
        loss = (loss_per_sample * W_t).sum() / W_t.sum()
        loss.backward()
        optimizer.step()

    print(f"[OutcomeNN] user {user_id}: training done, final loss {loss.item():.4f}")

    # Save model + normalisation
    save_path = os.path.join(_model_dir(user_id), "outcome_nn.pt")
    torch.save(
        {
            "state_dict": model.state_dict(),
            "n_features": n_features,
            "n_outcomes": n_outcomes,
            "x_mean": X_mean.tolist(),
            "x_std": X_std.tolist(),
            "feature_names": feature_names,
            "outcome_names": outcome_names,
        },
        save_path,
    )

    # Evaluate NN vs ML MAE on held-out real data (simple train-set estimate)
    model.eval()
    with torch.no_grad():
        X_real_s = (X_real - X_mean) / X_std
        nn_pred = model(torch.FloatTensor(X_real_s)).numpy()
        nn_mae = float(np.abs(Y_real - nn_pred).mean())

    ml_suite = load_outcome_models(user_id)
    if ml_suite is not None:
        from backend.outcome_models import predict_from_suite

        ml_preds = np.array([
            list(predict_from_suite(ml_suite, x).values())
            for x in X_real
        ])
        ml_mae = float(np.abs(Y_real - ml_preds).mean())
        gain_pct = thresholds["nn_accuracy_gain_pct"]
        win = ml_mae > 0 and (ml_mae - nn_mae) / ml_mae * 100 >= gain_pct
        record_nn_comparison(user_id, nn_mae=nn_mae, ml_mae=ml_mae, win=win)
        print(f"[OutcomeNN] NN MAE={nn_mae:.4f} ML MAE={ml_mae:.4f} win={win}")

    return True


# ---------------------------------------------------------------------------
# Inference helper
# ---------------------------------------------------------------------------

def predict_from_nn(user_id: int, x_features: np.ndarray) -> dict[str, float] | None:
    """Load outcome NN and predict biomarker deltas for one feature vector.

    Returns None if the NN model file does not exist.
    """
    import torch

    nn_path = os.path.join(MODELS_ROOT, f"user_{user_id}", "outcome_nn.pt")
    if not os.path.exists(nn_path):
        return None

    try:
        checkpoint = torch.load(nn_path, map_location="cpu", weights_only=True)
        n_features = checkpoint["n_features"]
        n_outcomes = checkpoint["n_outcomes"]
        outcome_names = checkpoint["outcome_names"]
        x_mean = np.array(checkpoint["x_mean"])
        x_std  = np.array(checkpoint["x_std"])

        model = _build_model(n_features, n_outcomes)
        model.load_state_dict(checkpoint["state_dict"])
        model.eval()

        x_s = (x_features - x_mean) / np.where(x_std < 1e-8, 1.0, x_std)
        with torch.no_grad():
            pred = model(torch.FloatTensor(x_s)).numpy()

        return {name: float(pred[i]) for i, name in enumerate(outcome_names)}
    except Exception as e:
        print(f"[OutcomeNN] predict error for user {user_id}: {e}")
        return None
